USE adlister_db;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE categories;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS users(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(100),
  password VARCHAR(100),
  display_name VARCHAR(100),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ads(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(100),
  description TEXT,
  user_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS categories(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category VARCHAR(100),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ad_category(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ad_id INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (ad_id) REFERENCES ads(id),
  FOREIGN KEY (category_id) REFERENCES categories(id)
);